Allows for excluding spell id's from the module.
azerothcore/mod-account-mounts pull request #12
Opened 2024-01-31 21:48 UTC by blkht01

## Changes Proposed:
- Allow to exclude spell ids from the module
- 

## Issues Addressed:

- Closes

## SOURCE:

## Tests Performed:

- yes, azcore run on linux
- 

## How to Test the Changes:

1. Add some mount spell ids to the config file
2. Login, learn spell on one character
3. Change characters and check that it is not available

2024-02-02 02:51 UTC, pangolp commented
All the changes that are optional, and that can be configured, allow the module to adapt to a greater number of servers. So I think the idea is good. It would be necessary to carry out tests on Windows as well, and see if it passes the tests.

2024-02-02 12:46 UTC, blkht01 commented
I don't think the clang fail has anything to do with my changes..? Unless I'm missing something.

I cloned a clean solution and added the module with my commits again to test and it builds fine for me on Ubuntu 22.04.

Edit: I don't have the ability to test on windows unfortunately.

2024-02-02 12:57 UTC, pangolp commented
> I don't think the clang fail has anything to do with my changes..? Unless I'm missing something.
> 
> I cloned a clean solution and added the module with my commits again to test and it builds fine for me on Ubuntu 22.04.
> 
> Edit: I don't have the ability to test on windows unfortunately.

Once it is finished and has passed all the tests, I will be in charge of testing it in Windows. Although it would be good if you added an example of how to test it and that the list is empty by default. Let each project decide whether or not to add spells to it or leave it empty.

2024-02-02 18:13 UTC, blkht01 commented
> list is empty by default. Let each project decide whether or not to add spells to it or leave it empty.

Good idea, I added this.

2024-02-03 10:16 UTC, pangolp commented
Thanks for the changes, and for the modification in the pull request adding new information to better understand and test. When I pass the tests, I will try to review it in Windows, to see how it works. Although I did not know this module and I started working on another one, which works differently. If you want to review it and make modifications, the link is also in the README of the repository.

2024-02-03 10:21 UTC, pangolp approved these changes
I haven't tested the code yet, but the changes I proposed were made. Once the tests have been carried out in the repository, I will test it in Windows to rule out any errors. Thank you for collaborating with the module and the community.

2024-02-03 10:21 UTC, pangolp commented on conf/mod_account_mount.conf.dist
> +Account.Mounts.ExcludedSpellIDs = 470,578,6777,66847,17464,18989,10969,10796,35020,34406
Leave a line break at the end of the document, so that the error here on Github disappears and by default, the list should be empty to prevent all projects from having these spells added that they may not want to have.

2024-02-03 10:51 UTC, pangolp commented
```
/home/runner/work/mod-account-mounts/mod-account-mounts/modules/mod-account-mounts/src/mod_account_mount.cpp:18:53: fatal error: 'GetStringDefault' is deprecated: Use GetOption<std::string> instead [-Wdeprecated-declarations]
        std::string excludedSpellsStr = sConfigMgr->GetStringDefault("Account.Mounts.ExcludedSpellIDs", "");
                                                    ^
/home/runner/work/mod-account-mounts/mod-account-mounts/src/common/Configuration/Config.h:57:7: note: 'GetStringDefault' has been explicitly marked deprecated here
    [[deprecated("Use GetOption<std::string> instead")]]
      ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:104: modules/CMakeFiles/modules.dir/mod-account-mounts/src/mod_account_mount.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1199: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

2024-02-03 10:52 UTC, pangolp requested changes

2024-02-03 10:52 UTC, pangolp commented on src/mod_account_mount.cpp
> +        std::string excludedSpellsStr = sConfigMgr->GetStringDefault("Account.Mounts.ExcludedSpellIDs", "");
fatal error: 'GetStringDefault' is deprecated

2024-02-03 10:54 UTC, pangolp commented on src/mod_account_mount.cpp
> +        std::string excludedSpellsStr = sConfigMgr->GetStringDefault("Account.Mounts.ExcludedSpellIDs", "");
```c++
std::string excludedSpellsStr = sConfigMgr->GetOption<std::string>("Account.Mounts.ExcludedSpellIDs", "");
```

2024-02-03 11:00 UTC, pangolp approved these changes

2024-02-03 11:29 UTC, pangolp commented
Thank you for your contribution.

2024-02-03 11:29 UTC, merged